// Code generated by scripts/sync-go.mjs from Go reflect scan. DO NOT EDIT.
import { Kind } from './kind.js';
import { Type, anyType } from './type.js';

export interface StdTypeDescriptor { name: string; pkgPath: string; kind: string; string: string; comparable: boolean }
export const STD_TYPE_DESCRIPTORS: StdTypeDescriptor[] = [
  {
    "comparable": true,
    "kind": "struct",
    "name": "Time",
    "pkgPath": "time",
    "string": "time.Time"
  },
  {
    "comparable": true,
    "kind": "int64",
    "name": "Duration",
    "pkgPath": "time",
    "string": "time.Duration"
  },
  {
    "comparable": false,
    "kind": "slice",
    "name": "",
    "pkgPath": "",
    "string": "[]interface {}"
  },
  {
    "comparable": false,
    "kind": "map",
    "name": "",
    "pkgPath": "",
    "string": "map[string]interface {}"
  },
  {
    "comparable": false,
    "kind": "func",
    "name": "",
    "pkgPath": "",
    "string": "func(interface {}) bool"
  }
];

export function StdType(name: string): Type {
  const d = STD_TYPE_DESCRIPTORS.find((item) => item.string === name || item.name === name);
  if (!d) return anyType;
  const kind = d.kind === 'struct' ? Kind.Struct : d.kind === 'int64' ? Kind.Int64 : d.kind === 'slice' ? Kind.Slice : d.kind === 'map' ? Kind.Map : d.kind === 'func' ? Kind.Func : Kind.Interface;
  return new Type(kind, d.string);
}
