// Code generated by scripts/gen-helpers.mjs. DO NOT EDIT.
// Port of expr-lang/expr vm/runtime/helpers[generated].go
//
// Generator mirrors Go template structure with JS type domain:
// Go: 13 numeric types → 169 type-pair arms per operator
// JS: 2 numeric types → 4 type-pair arms per operator
// All arms are reachable. No dead code.

export function Equal(a: any, b: any): boolean {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a === b;
        case "number":
          return Number(a) === Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) === Number(b);
        case "number":
          return Number(a) === Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a === b;
      break;
    case "boolean":
      if (typeof b === "boolean") return a === b;
      break;
  }
  if (a === null && b === null) return true;
  if (a === undefined && b === undefined) return true;
  if (a === null && b === undefined) return true;
  if (a === undefined && b === null) return true;
  return JSON.stringify(a) === JSON.stringify(b);
}

export function Less(a: any, b: any): boolean {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a < b;
        case "number":
          return Number(a) < Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) < Number(b);
        case "number":
          return Number(a) < Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a < b;
      break;
  }
  throw new Error(`invalid operation: ${typeof a} < ${typeof b}`);
}

export function More(a: any, b: any): boolean {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a > b;
        case "number":
          return Number(a) > Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) > Number(b);
        case "number":
          return Number(a) > Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a > b;
      break;
  }
  throw new Error(`invalid operation: ${typeof a} > ${typeof b}`);
}

export function LessOrEqual(a: any, b: any): boolean {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a <= b;
        case "number":
          return Number(a) <= Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) <= Number(b);
        case "number":
          return Number(a) <= Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a <= b;
      break;
  }
  throw new Error(`invalid operation: ${typeof a} <= ${typeof b}`);
}

export function MoreOrEqual(a: any, b: any): boolean {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a >= b;
        case "number":
          return Number(a) >= Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) >= Number(b);
        case "number":
          return Number(a) >= Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a >= b;
      break;
  }
  throw new Error(`invalid operation: ${typeof a} >= ${typeof b}`);
}

export function Add(a: any, b: any): any {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a + b;
        case "number":
          return Number(a) + Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) + Number(b);
        case "number":
          return Number(a) + Number(b);
      }
      break;

    case "string":
      if (typeof b === "string") return a + b;
      break;
  }
  throw new Error(`invalid operation: ${typeof a} + ${typeof b}`);
}

export function Subtract(a: any, b: any): any {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a - b;
        case "number":
          return Number(a) - Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) - Number(b);
        case "number":
          return Number(a) - Number(b);
      }
      break;

  }
  throw new Error(`invalid operation: ${typeof a} - ${typeof b}`);
}

export function Multiply(a: any, b: any): any {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return a * b;
        case "number":
          return Number(a) * Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) * Number(b);
        case "number":
          return Number(a) * Number(b);
      }
      break;

  }
  throw new Error(`invalid operation: ${typeof a} * ${typeof b}`);
}

export function Divide(a: any, b: any): number {
  switch (typeof a) {
    case "bigint":
      switch (typeof b) {
        case "bigint":
          return Number(a) / Number(b);
        case "number":
          return Number(a) / Number(b);
      }
      break;
    case "number":
      switch (typeof b) {
        case "bigint":
          return Number(a) / Number(b);
        case "number":
          return Number(a) / Number(b);
      }
      break;

  }
  throw new Error(`invalid operation: ${typeof a} / ${typeof b}`);
}

export function Modulo(a: any, b: any): bigint {
  switch (typeof a) {
    case "bigint":
      if (typeof b === "bigint") {
        return a % b;
      }
      break;

  }
  throw new Error(`invalid operation: ${typeof a} % ${typeof b}`);
}

