// Code generated by scripts/sync-go.mjs from references/expr/patcher/value/value.go. DO NOT EDIT.
export const VALUER_METHODS = [
  "AsAny",
  "AsBool",
  "AsInt",
  "AsInt8",
  "AsInt16",
  "AsInt32",
  "AsInt64",
  "AsUint",
  "AsUint8",
  "AsUint16",
  "AsUint32",
  "AsUint64",
  "AsFloat32",
  "AsFloat64",
  "AsString",
  "AsTime",
  "AsDuration",
  "AsArray",
  "AsMap"
] as const;
